# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
# Explanation:
# 'e' is the letter that was added.

class Solution(object):
    # 37%
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        array1={}
        array2={}
        for i in range(ord('a'),ord('z')+1):
            array1[chr(i)]=0
            array2[chr(i)]=0

        for c in s:
            count=array1[c]
            array1[c]=count+1

        for c in t:
            count=array2[c]
            array2[c]=count+1

        for i in range(ord('a'), ord('z')+1):
            c=chr(i)
            if not array1[c]==array2[c]:
                return c

    # beat 90%
    def findTheDifference2(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        content=s+t
        for i in t:
            if content.count(i) % 2:
                return i

sol=Solution()
s="abcd"
t="abecd"
print(sol.findTheDifference2(s,t))
